# Generated by Django 4.2 on 2023-04-24 15:34

from django.db import migrations
import hashlib
from users.models import UserAPIKey

def create_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    secret = 'abcdef123456'
    hashed_secret = hashlib.sha256(secret.encode('utf-8')).hexdigest()
    User(name="Joe Silver", secret=hashed_secret).save()
    api_key, key = UserAPIKey.objects.create_key(name='Joe Silver', user_id=1)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_api_userapikey'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
