# Generated by Django 4.2 on 2023-04-24 15:34

from django.db import migrations
from users.models import UserAPIKey

def create_data(apps, schema_editor):
    UserAPIKey.objects.filter(user_id=1).delete()
    api_key, key = UserAPIKey.objects.create_key(name='Joe Silver', user_id=1)
    print(api_key)
    print(key)
    with open('data.txt', 'w') as f:
        f.write(f'{api_key}\n{key}')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]