# Generated by Django 4.2 on 2023-04-25 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userapikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='users.user'),
        ),
    ]
